webstraunt_items = {
    "Snack Bowls": "https://www.webstaurantstore.com/dart-ctr12bd-safeseal-12-oz-plastic-tamper-resistant-tamper-evident-bowl-with-dome-lid-case/301CTR12BD.html",
    "Regular Bowls": "https://www.webstaurantstore.com/dart-ctr16bd-safeseal-16-oz-plastic-tamper-resistant-tamper-evident-bowl-with-dome-lid-case/301CTR16BD.html",
    "Jumbo Bowls": "https://www.webstaurantstore.com/dart-ctr24bd-safeseal-24-oz-plastic-tamper-resistant-tamper-evident-bowl-with-dome-lid-case/301CTR24BD.html",
    "Regular Smoothie Cups": "https://www.webstaurantstore.com/choice-16-oz-clear-pet-plastic-cold-cup-case/500CC16.html",
    "Jumbo Smoothie Cups": "https://www.webstaurantstore.com/choice-24-oz-clear-pet-plastic-cold-cup-case/500CC24.html",
    "Smoothie Lids": "https://www.webstaurantstore.com/choice-9-12-16-20-and-24-oz-clear-flat-lid-with-straw-slot-case/500LFLAT.html",
    "Smoothie Straws": "https://www.webstaurantstore.com/choice-8-1-2-colossal-neon-wrapped-straw-bag/999COLWNEON.html",
    "Smoothie Trays": "https://www.webstaurantstore.com/pulp-fiber-4-cup-carrier-case/433CARRIER4.html",
    "Napkins": "https://www.webstaurantstore.com/10-x-12-white-1-4-fold-luncheon-napkin-case/5001N6001.html",
    "Paper Bags": "https://www.webstaurantstore.com/choice-8-x-4-1-2-x-10-1-4-natural-kraft-paper-shopping-bag-with-handles-case/433BR8510C.html",
    "Big Paper Bags": "https://www.webstaurantstore.com/choice-10-x-6-3-4-x-12-natural-kraft-paper-shopping-bag-with-handles-case/433BR10712C.html",
    "Spoons": "https://www.webstaurantstore.com/ecochoice-heavy-weight-compostable-6-1-2-green-cpla-plastic-spoon-case/130GHWPLASPN.html",
    "Brown paper towels": "https://www.webstaurantstore.com/lavex-janitorial-800-natural-brown-kraft-hardwound-roll-paper-towel-case/5001RT800N.html",
    "Monin DragonFruit": "https://www.webstaurantstore.com/monin-1-liter-premium-dragon-fruit-flavoring-syrup/544SYPFR298F.html",
    "1 Liter Monin Agave": "https://www.webstaurantstore.com/monin-1-liter-organic-agave-nectar-sweetener-syrup/544SYPFL157F.html",
    "Monin Wildberry": "https://www.webstaurantstore.com/monin-1-liter-premium-wildberry-flavoring-syrup/544SYPFR114F.html",
    "Empty Drizzle Bottles": "https://www.webstaurantstore.com/tablecraft-12463cf-24-oz-selectop-wide-mouth-dualway-first-in-first-out-fifo-squeeze-bottle-with-cone-tip-opening-pack/80812463CF.html",
    "Scouring Pads": "https://www.webstaurantstore.com/lavex-janitorial-9-x-6-x-3-8-medium-duty-dark-green-scouring-pad-pack/483MDDGSCOUR.html",
    "Sample Cups": "https://www.webstaurantstore.com/choice-4-oz-clear-plastic-souffle-cup-portion-cup-pack/999P400C.html",
    "Sample Lids": "https://www.webstaurantstore.com/choice-pet-plastic-lid-for-3-25-to-5-5-oz-souffle-cup-portion-cup-pack/999PL400.html"
}


misc_webstaurant_items = {
    "Long Fruit Tubs": "https://www.webstaurantstore.com/cambro-36pp190-1-3-size-translucent-food-pan-6-deep/21436PP.html",
    "Small Deep Dry Topping Tubs": "https://www.webstaurantstore.com/cambro-66pp190-1-6-size-translucent-food-pan-6-deep/21466PP.html",
    "Small Shallow Dry Topping Tubs": "https://www.webstaurantstore.com/cambro-62pp190-1-6-size-translucent-food-pan-2-1-2-deep/21462PP.html",
    "Fruit Container Lids": "https://www.webstaurantstore.com/cambro-30ppcwsc190-camwear-1-3-size-translucent-seal-cover/21430SCWH.html",
    "Dry Topping Container Lids": "https://www.webstaurantstore.com/cambro-60ppcwsc190-camwear-1-6-size-translucent-seal-cover/21460SCWH.html",
    "Thermometers": "https://www.webstaurantstore.com/avatemp-2-1-2-dial-refrigerator-freezer-thermometer/9142DRFTA.html",
    "Squeegees": "https://www.webstaurantstore.com/carlisle-36682400-flo-pac-22-double-foam-heavy-duty-floor-squeegee-with-metal-frame/27136682400.html",
    "Blender Jugs": "https://www.webstaurantstore.com/vitamix-1194-64-oz-blender-jar-with-wet-blade-for-vita-prep-and-vita-pro-series/9651194.html",
    "Teaspoon Measuring Spoons": "https://www.webstaurantstore.com/vollrath-47118-four-piece-round-measuring-spoon-set/92247118.html",
    "Tablespoon Measuring Spoons": "https://www.webstaurantstore.com/vollrath-47118-four-piece-round-measuring-spoon-set/92247118.html",
    "1/8 Measuring Spoons": "https://www.webstaurantstore.com/1-8-cup-stainless-steel-measuring-scoop/407SLMS013V.html",
    "1/4 Measuring Cups": "https://www.webstaurantstore.com/american-metalcraft-mcl14-1-4-cup-stainless-steel-measuring-cup-with-wire-handle/124MCL14.html",
    "1/3 Measuring Cups": "https://www.webstaurantstore.com/american-metalcraft-mcl13-1-3-cup-stainless-steel-measuring-cup-with-wire-handle/124MCL13.html",
    "1/2 Measuring Cups": "https://www.webstaurantstore.com/american-metalcraft-mcl12-1-2-cup-stainless-steel-measuring-cup-with-wire-handle/124MCL12.html",
    "1 Measuring Cups": "https://www.webstaurantstore.com/american-metalcraft-mcl10-1-cup-stainless-steel-measuring-cup-with-wire-handle/124MCL10.html",
    "Liquid Measuring Cups": "https://www.webstaurantstore.com/webstaurantstore-1-cup-clear-polycarbonate-measuring-cup/6903210WEB.html",
    "Chia Seed Cups": "https://www.webstaurantstore.com/cambro-96skrm135-camwear-10-oz-polycarbonate-shaker-with-rose-lid-for-medium-ground-product/21496SKRM.html",
    "Hemp & Flax Seed Cups": "https://www.webstaurantstore.com/cambro-96skrc135-camwear-10-oz-polycarbonate-shaker-with-yellow-lid-for-cheese/21496SKRC.html",
    "Sanitizer Bins": "https://www.webstaurantstore.com/noble-products-3-qt-red-sanitizing-pail/511KP97RDNBL.html",
    "Detergent Bins": "https://www.webstaurantstore.com/noble-products-3-qt-green-cleaning-pail/511KP97GNNBL.html",
    "Bartender Spoons": "https://www.webstaurantstore.com/choice-11-bar-spoon-with-red-knob/176BARSPN11.html",
    "Ice Cream Scoops": "https://www.webstaurantstore.com/oxo-11295000-good-grips-20-stainless-steel-ice-cream-scoop-1-6-oz/29711295000.html",
    "Spades": "https://www.webstaurantstore.com/9-stainless-steel-white-ice-cream-spade/407SLTHCS001.html",
    "Pitcher for Bases": "https://www.webstaurantstore.com/webstaurantstore-4-qt-clear-polycarbonate-measuring-cup/6903218WEB.html",
    "Stock Pots": "https://www.webstaurantstore.com/choice-80-qt-standard-weight-aluminum-stock-pot/471SP80QT.html",
    "Drain Pan (For Pineapple)": "https://www.webstaurantstore.com/carlisle-3067007-storplus-1-3-size-clear-polycarbonate-drain-tray/70030D.html",
    "Fridge/Freezer Clips": "https://www.webstaurantstore.com/avantco-178clip-refrigeration-shelf-clip/178CLIP.html",
    "Strawberry/Banana Knives": "https://www.webstaurantstore.com/mercer-culinary-m33912b-4-red-non-stick-paring-knife-with-sheath/470M33912B.html",
    "Kiwi Knives": "https://www.webstaurantstore.com/schraf-5-granton-edge-santoku-knife-with-tprgrip-handle/220KVSNTKGE5.html",
    "Mango Knives": "https://www.webstaurantstore.com/schraf-7-granton-edge-santoku-knife-with-tprgrip-handle/220VSNTKUGE7.html",
    "Pineapple Knives": "https://www.webstaurantstore.com/schraf-9-granton-edge-santoku-knife-with-tprgrip-handle/220KVSNTKGE9.html",
    "Small Cutting Boards": "https://www.webstaurantstore.com/choice-10-x-6-x-1-2-white-polyethylene-cutting-board/4071065WH.html",
    "Medium Cutting Boards": "https://www.webstaurantstore.com/choice-18-x-12-x-1-2-white-polyethylene-cutting-board/40718125WH.html",
    "Large Cutting Boards": "https://www.webstaurantstore.com/choice-24-x-18-x-1-2-white-polyethylene-cutting-board/40724185WH.html",
    "Bowl for Strawberries/Blueberries": "https://www.webstaurantstore.com/oxo-1059701-good-grips-5-qt-white-plastic-mixing-bowl-with-non-slip-base/2971059701.html",
    "Drain Plugs (For Sink)": "https://www.webstaurantstore.com/regency-3-1-2-basket-strainer-fixed-post/600DBS312.html",
    "Dust Pans": "https://www.webstaurantstore.com/rubbermaid-fg253100bla-lobby-pro-plastic-upright-dust-pan/6902531.html",
    "Big Metal Scoop": "https://www.webstaurantstore.com/choice-24-oz-one-piece-aluminum-scoop/407ALSC24.html",
    "Immersion Blender Machine": "https://www.webstaurantstore.com/waring-wsbppwa-big-stik-variable-speed-immersion-blender-with-10-whisk-1-hp/929WSBPPWA.html",
    "Immersion Blender Stick": "https://www.webstaurantstore.com/waring-wsb70st-21-stainless-steel-shaft-for-big-stix-heavy-duty-immersion-blenders/929WSB70ST.html"
}

